---
language: android

android:
  components:
    - build-tools-27.0.3
    - android-28

addons:
  apt:
    packages:
      - python3.6
    sources:
      - sourceline: ppa:jonathonf/python-3.6

before_install: echo 'android { defaultConfig { python { buildPython "python3.6" } } }' >> app/build.gradle
